const languages = [
  { code: "af-ZA",       name: "Afrikaans" },
  { code: "am-ET",       name: "Amharic" },
  { code: "hy-AM",       name: "Armenian" },
  { code: "az-AZ",       name: "Azerbaijani" },
  { code: "id-ID",       name: "Indonesian" },
  { code: "ms-MY",       name: "Malay" },
  { code: "bn-BD",       name: "Bengali (Bangladesh)" },
  { code: "bn-IN",       name: "Bengali (India)" },
  { code: "ca-ES",       name: "Catalan" },
  { code: "cs-CZ",       name: "Czech" },
  { code: "da-DK",       name: "Danish" },
  { code: "de-DE",       name: "German" },
  { code: "en-AU",       name: "English (Australia)" },
  { code: "en-GB",       name: "English (United Kingdom)" },
  { code: "en-US",       name: "English (United States)" },
  { code: "es-AR",       name: "Spanish (Argentina)" },
  { code: "es-BO",       name: "Spanish (Bolivia)" },
  { code: "es-CL",       name: "Spanish (Chile)" },
  { code: "es-CO",       name: "Spanish (Colombia)" },
  { code: "es-ES",       name: "Spanish (Spain)" },
  { code: "es-MX",       name: "Spanish (Mexico)" },
  { code: "es-PE",       name: "Spanish (Peru)" },
  { code: "es-UY",       name: "Spanish (Uruguay)" },
  { code: "eu-ES",       name: "Basque (Spain)" },
  { code: "fil-PH",      name: "Filipino" },
  { code: "fr-CA",       name: "French (Canada)" },
  { code: "fr-FR",       name: "French" },
  { code: "gl-ES",       name: "Galician" },
  { code: "ka-GE",       name: "Georgian" },
  { code: "gu-IN",       name: "Gujarati" },
  { code: "hr-HR",       name: "Croatian" },
  { code: "zu-ZA",       name: "Zulu" }
  { code: "is-IS",       name: "Icelandic" },
  { code: "it-IT",       name: "Italian" },
  { code: "jv-ID",       name: "Javanese" },
  { code: "kn-IN",       name: "Kannada" },
  { code: "km-KH",       name: "Khmer" },
  { code: "lo-LA",       name: "Lao" },
  { code: "lv-LV",       name: "Latvian" },
  { code: "lt-LT",       name: "Lithuanian" },
  { code: "hu-HU",       name: "Hungarian" },
  { code: "ml-IN",       name: "Malayalam" },
  { code: "mr-IN",       name: "Marathi" },
  { code: "nl-NL",       name: "Dutch" },
  { code: "ne-NP",       name: "Nepali" },
  { code: "nb-NO",       name: "Norwegian" },
  { code: "pl-PL",       name: "Polish" },
  { code: "pt-BR",       name: "Portuguese (Brazil)" },
  { code: "pt-PT",       name: "Portuguese (Portugal)" },
  { code: "ro-RO",       name: "Romanian" },
  { code: "si-LK",       name: "Sinhala" },
  { code: "sk-SK",       name: "Slovak" },
  { code: "sl-SI",       name: "Slovenian" },
  { code: "su-ID",       name: "Sundanese" },
  { code: "sw-TZ",       name: "Swahili (Tanzania)" },
  { code: "sw-KE",       name: "Swahili (Kenya)" },
  { code: "fi-FI",       name: "Finnish" },
  { code: "sv-SE",       name: "Swedish" },
  { code: "ta-IN",       name: "Tamil (India)" },
  { code: "ta-SG",       name: "Tamil (Singapore)" },
  { code: "ta-LK",       name: "Tamil (Sri Lanka)" },
  { code: "te-IN",       name: "Telugu" },
  { code: "vi-VN",       name: "Vietnamese" },
  { code: "tr-TR",       name: "Turkish" },
  { code: "ur-PK",       name: "Urdu" },
  { code: "el-GR",       name: "Greek" },
  { code: "bg-BG",       name: "Bulgarian" },
  { code: "ru-RU",       name: "Russian" },
  { code: "sr-RS",       name: "Serbian" },
  { code: "uk-UA",       name: "Ukrainian" },
  { code: "he-IL",       name: "Hebrew" },
  { code: "ar-AE",       name: "Arabic (United Arab Emirates)" },
  { code: "ar-EG",       name: "Arabic (Egypt)" },
  { code: "ar-MA",       name: "Arabic (Morocco)" },
  { code: "ar-MA",       name: "Arabic (Morocco)" },
  { code: "fa-IR",       name: "Persian/Farsi" },
  { code: "hi-IN",       name: "Hindi" },
  { code: "th-TH",       name: "Thai" },
  { code: "ko-KR",       name: "Korean" },
  { code: "cmn-Hant-TW", name: "Chinese (Mandarin)" },
  { code: "yue-Hant-HK", name: "Cantonese" },
  { code: "zh-TW", name: "Mandarin (Taiwan)" },
  { code: "ja-JP",       name: "Japanese (Japan)" },
  { code: "sq",          name: "Albanian" },
  { code: "bs",          name: "Bosnian" },
  { code: "my",          name: "Burmese (Myanmar)" },
  { code: "eo",          name: "Esperanto" },
  { code: "la",          name: "Latin" },
  { code: "mk",          name: "Macedonian" },
  { code: "cy",          name: "Welsh" }
];

function findByCode(code) {
  return this.find(l => l.code === code);
}

function findByName(name) {
  return this.find(l => l.name === name);
}

languages.findByCode = findByCode.bind(languages);
languages.findByName = findByName.bind(languages);

module.exports = languages;
